# Generated by Django 4.2.13 on 2024-07-08 16:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '__first__'),
        ('labels', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('ipi_code', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('isni_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('pro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Performing Rights Organization')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bio_description', models.TextField(blank=True, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='artist_backgrounds/')),
                ('recording_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='labels.label')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='artists.artist')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
            ],
        ),
    ]
