# Generated by Django 4.2.13 on 2024-07-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the partner.', max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='Country of the partner.', max_length=2, null=True)),
                ('website', models.URLField(blank=True, help_text='Website of the partner.', null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email of the partner.', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number of the partner.', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the partner.', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the partner.', null=True)),
                ('user', models.OneToOneField(help_text='The user who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
