# Generated by Django 4.2.13 on 2024-07-11 10:15

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('artists', models.ManyToManyField(related_name='albums', to='artists.artist')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='labels.label')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['title'],
            },
        ),
    ]
