# Generated by Django 4.2.13 on 2024-07-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('genres', '0001_initial'),
        ('artists', '0001_initial'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(related_name='related_albums', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(related_name='related_albums', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_albums', to='labels.label'),
        ),
    ]
