# Generated by Django 4.2.13 on 2024-07-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('isni', models.CharField(blank=True, help_text='Enter Number in Standard ISNI Notation [0000000123456789]', max_length=16, null=True)),
                ('ipn', models.CharField(blank=True, help_text='PayPal Email Address', max_length=255, null=True)),
                ('paypal_email', models.EmailField(blank=True, help_text='PayPal Email Address', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
