# Generated by Django 4.2.13 on 2024-07-08 16:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isrc', models.CharField(max_length=12, unique=True)),
                ('iswc', models.CharField(blank=True, max_length=11, null=True)),
                ('language', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('parental_advisory', models.CharField(choices=[('N', 'None'), ('E', 'Explicit'), ('C', 'Clean')], default='N', max_length=1)),
                ('available_for', models.CharField(choices=[('D', 'Download'), ('S', 'Stream')], default='S', max_length=1)),
                ('file', models.FileField(blank=True, null=True, upload_to='tracks/')),
                ('artists', models.ManyToManyField(related_name='tracks', to='artists.artist')),
                ('featured_artists', models.ManyToManyField(blank=True, related_name='featured_tracks', to='artists.artist')),
                ('genres', models.ManyToManyField(related_name='tracks', to='genres.genre')),
            ],
        ),
    ]
