# Generated by Django 4.2.13 on 2024-07-11 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('artists', '0002_remove_artist_genre_artist_genres'),
        ('albums', '0002_remove_album_genre_album_genres_alter_album_artists_and_more'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, help_text='Album in which the track is included.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='albums.album'),
        ),
        migrations.AddField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, help_text='Beats per minute (tempo) of the track.', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='composer',
            field=models.CharField(blank=True, help_text='Composer of the track.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='copyright_info',
            field=models.TextField(blank=True, help_text='Copyright information for the track.', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_art',
            field=models.ImageField(blank=True, help_text='Cover art image for the track.', null=True, upload_to='cover_arts/'),
        ),
        migrations.AddField(
            model_name='track',
            name='credits',
            field=models.TextField(blank=True, help_text='Additional credits for contributors.', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the track.', null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='key',
            field=models.CharField(blank=True, help_text='Musical key of the track.', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='release_date',
            field=models.DateField(blank=True, help_text='Release date of the track.', null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(help_text='Artists who performed the track.', related_name='tracks', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='available_for',
            field=models.CharField(choices=[('D', 'Download'), ('S', 'Stream')], default='S', help_text='Availability of the track for download or streaming.', max_length=1),
        ),
        migrations.AlterField(
            model_name='track',
            name='featured_artists',
            field=models.ManyToManyField(blank=True, help_text='Artists who are featured in the track.', related_name='featured_tracks', to='artists.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, help_text='File upload for the track.', null=True, upload_to='tracks/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.ManyToManyField(help_text='Genres associated with the track.', related_name='tracks', to='genres.genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='isrc',
            field=models.CharField(help_text='International Standard Recording Code.', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='iswc',
            field=models.CharField(blank=True, help_text='International Standard Musical Work Code.', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='language',
            field=models.CharField(blank=True, help_text='Language of the track, represented by ISO code.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='parental_advisory',
            field=models.CharField(choices=[('N', 'None'), ('E', 'Explicit'), ('C', 'Clean')], default='N', help_text='Parental advisory status.', max_length=1),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(help_text='The name of the track.', max_length=255),
        ),
    ]
