# Generated by Django 4.2.13 on 2024-07-08 16:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
