# Generated by Django 4.2.13 on 2024-07-11 10:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyricist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the lyricist.', max_length=100)),
                ('last_name', models.CharField(help_text='Last name of the lyricist.', max_length=100)),
                ('birth_date', models.DateField(blank=True, help_text='Birth date of the lyricist.', null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, help_text='Nationality of the lyricist.', max_length=2, null=True)),
                ('biography', models.TextField(blank=True, help_text='Biography of the lyricist.', null=True)),
                ('website', models.URLField(blank=True, help_text='Official website of the lyricist.', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the lyricist.', null=True, upload_to='lyricists/')),
            ],
        ),
    ]
