# Generated by Django 4.2.13 on 2024-07-11 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_album_track_bpm_track_composer_and_more'),
        ('lyrics', '0003_lyricist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyrics',
            name='lyricist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='lyrics.lyricist'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='tracks.track'),
        ),
    ]
