# Generated by Django 4.2.13 on 2024-07-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
        ('albums', '0002_remove_album_genre_album_genres_alter_album_artists_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dolby_atmos', models.BooleanField(default=False, help_text='Indicates if the release is in Dolby Atmos format.')),
                ('date_original_release', models.DateField(help_text='Original release date.')),
                ('album', models.ForeignKey(help_text='Related album.', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='albums.album')),
                ('partner', models.ForeignKey(help_text='Related album.', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, help_text='The date and time of the change.')),
                ('change_description', models.TextField(help_text='Description of the change.')),
                ('changed_by', models.OneToOneField(help_text='The user who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(help_text='Related release.', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='releases.release')),
            ],
        ),
    ]
