# Generated by Django 4.2.13 on 2024-07-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasePlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.ForeignKey(help_text='Related release.', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='platforms.platform')),
                ('release', models.ForeignKey(help_text='Related release.', on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='releases.release')),
            ],
        ),
    ]
