# Generated by Django 4.2.13 on 2024-07-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0002_releaseplatform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now=True, help_text='The date when the review was last updated.')),
                ('date_added', models.DateField(auto_now_add=True, help_text='The date when the review was added.')),
                ('release_date', models.DateField(help_text='The release date of the reviewed item.')),
                ('release', models.ForeignKey(help_text='Related release.', on_delete=django.db.models.deletion.CASCADE, related_name='releases_reviews', to='releases.release')),
            ],
        ),
    ]
